---
- name: Create user if not exists  
  user: # Utilizing the built in 'user' module
    name: "{{ username }}"  # The name of the user to create
    password: "{{ random_pass }}"  # The password for the user. It's randomly generated below in the random_pass variable
    shell: /bin/bash  # The default shell for the user
    comment: "Public kiosk user"  # A description or comment about the user
    create_home: yes  # This ensures a home directory is created for the user
  vars:  
    random_pass: "{{ lookup('password', '/dev/null length=20 chars=ascii_lowercase,ascii_uppercase,digits') }}"  # This generates a random password using the 'ansible.builtin.password' module