name: Requirement specification
description: Submit a requirement
title: "[Requirement]: "
labels: ["epic"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Please register the user story behind the requirement below!
  - type: textarea
    id: user-story
    attributes:
      label: Register user story for requirement
      description: Also tell us, what did you expect to happen?
      placeholder: |
        - Who is the user? (Stakeholder, persona, role)
        - What do they want to do? (Action)
        - Why do they want to do it? (Value or Justification)
      value: ""
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
