name: What problem needs to be solved?
description: Submit a User Story describing what challenge or problem needs to be adressed or solved
title: "User Story"
labels: ["epic"]
body:
  - type: markdown
    attributes:
      value: |
        Please register the user story below!
  - type: textarea
    id: user-story
    attributes:
      label: Register user story for requirement
      description: Also tell us, what did you expect to happen?
      placeholder: |
        AS A {user|persona|system},
        [INSTEAD OF {current condition}]
        I WANT TO {action}
        [SO THAT {value or justification}]
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
